/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

public class GameOfLife {

    public GameOfLife(int i, int j) {
        //TODO Auto-generated constructor stub
    }

    public int countLivingNeighbours(int i, int j) {
        // TODO Auto-generated method stub
        return 1;
    }

    public int[] getGridSize() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getGridSize'");
    }

    public Object setLivingCell(int i, int j) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'setLivingCell'");
    }

}
