/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

public class GameOfLife {

    public GameOfLife(int row, int column) {
        //TODO Auto-generated constructor stub
    }

    public int countLivingNeighbours(int row, int column) {
        // TODO Auto-generated method stub
        return 1;
    }

    public int[] getGridSize() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getGridSize'");
    }

    public Object setLivingCell(int row, int column) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'setLivingCell'");
    }

    public boolean isAlived(int row, int column) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'isAlived'");
    }

    public void nextGeneration() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'nextGeneration'");
    }

}
