/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game.of.life;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.util.HashMap;
import java.util.Map;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;

class GameOfLifeTest {
    @BeforeEach public void before() {
        gameOfLife = new GameOfLife(4, 8);
    }
    
    @Nested
    class Initialization {
        /**
         * L'application doit s'initialisée
         */
        @Test void gameOfLifeIsInitialized() {
            assertNotNull(gameOfLife);
            assertArrayEquals(new int[]{4, 8}, gameOfLife.getGridSize());
        }
    
        /**
         * Toutes les cellules doivent être initialisées mortes
         * @throws OutOfRangeException 
         */
        @Test void allCellsInitializedAsEmpty() throws OutOfRangeException {
            Map<String, Boolean> aliveCellsByCoords = new HashMap<>();
            for (int row = 0; row < 4; row++) {
                for (int column = 0; column < 8; column++) {
                    boolean aliveCells = gameOfLife.isAlive(row, column);
                    aliveCellsByCoords.put(row + "," + column, aliveCells);
                }
            }
            Boolean sum = aliveCellsByCoords.values().stream().allMatch(value -> !value);
            assertTrue(sum, aliveCellsByCoords.toString());
        }
    }

    @Nested
    class AlterationAndControls {
        /**
         * Modifier l’état d'une cellule et récupérer son état 
         * @throws OutOfRangeException 
         */
        @Test void canAlterCellState() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
    
            assertTrue(gameOfLife.isAlive(0, 0));
        }
    
        /**
         * Demander une opération sur une cellule hors grille lance une exception
         */
        @Test void outOfRangeSetLivingCell() {
            assertThrows(OutOfRangeException.class, () -> gameOfLife.setLivingCell(-1, 0));
            assertThrows(OutOfRangeException.class, () -> gameOfLife.setLivingCell(8, 4));
            assertThrows(OutOfRangeException.class, () -> gameOfLife.setLivingCell(8, 4));
        }
    
        /**
         * Demander une opération sur une cellule hors grille lance une exception
         */
        @Test void outOfRangeCountLivingNeighbors() {
            assertThrows(OutOfRangeException.class, () -> gameOfLife.countLivingNeighbors(-1, 0));
            assertThrows(OutOfRangeException.class, () -> gameOfLife.countLivingNeighbors(8, 4));
            assertThrows(OutOfRangeException.class, () -> gameOfLife.countLivingNeighbors(8, 4));
        }
        
        /**
         * Le compte de voisin vivant est opérationnel pour une cellule
         * @throws OutOfRangeException 
         */
        @Test void countOneLivingNeighbor() throws OutOfRangeException {
            gameOfLife.setLivingCell(1,1);
    
            // La cellule ne se compte pas elle même
            assertEquals(0, gameOfLife.countLivingNeighbors(1, 1));
            
            // Les 8 Voisins
            assertEquals(1, gameOfLife.countLivingNeighbors(0, 0));
            assertEquals(1, gameOfLife.countLivingNeighbors(0, 1));
            assertEquals(1, gameOfLife.countLivingNeighbors(0, 2));
            assertEquals(1, gameOfLife.countLivingNeighbors(1, 0));
            
            assertEquals(1, gameOfLife.countLivingNeighbors(1, 2));
            assertEquals(1, gameOfLife.countLivingNeighbors(2, 0));
            assertEquals(1, gameOfLife.countLivingNeighbors(2, 1));
            assertEquals(1, gameOfLife.countLivingNeighbors(2, 2));
        }
    
        /**
         * Le compte est opérationnel pour plus d'une cellule vivante
         * @throws OutOfRangeException 
         */
        @Test void countLivingNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(1,1);
            gameOfLife.setLivingCell(2,2);
    
            // La cellule ne se compte pas elle même
            assertEquals(1, gameOfLife.countLivingNeighbors(1, 1));
            assertEquals(1, gameOfLife.countLivingNeighbors(2, 2));
            
            // Les Voisins
            assertEquals(2, gameOfLife.countLivingNeighbors(2, 1));
            assertEquals(2, gameOfLife.countLivingNeighbors(1, 2));
    
            assertEquals(1, gameOfLife.countLivingNeighbors(0, 2));
            assertEquals(1, gameOfLife.countLivingNeighbors(3, 2));
        } 
    
        /**
         * CountLivingNeighbors fonctionne dans les coins
         * @throws OutOfRangeException 
         */
        @Test void countLivingNeighborsInCorners() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 1);
            gameOfLife.setLivingCell(1, 1);
            gameOfLife.setLivingCell(1, 0);
    
            assertEquals(3, gameOfLife.countLivingNeighbors(0, 0));
        }
    }

    @Nested
    class NextGenerationComputing {
        /**
         * Nouvelle Génération - Test livingNeighbors < 2 alors on meurt
         * @throws OutOfRangeException 
         */
        @Test void lessThanTwoLivingNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
    
            assertTrue(gameOfLife.isAlive(0, 0));
            gameOfLife.nextGeneration();
            assertFalse(gameOfLife.isAlive(0, 0));
        }
    
        /**
         * Nouvelle Génération - Surpopulation
         * @throws OutOfRangeException 
         */
        @Test void moreThanThreeLivingNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
            gameOfLife.setLivingCell(0, 1);
            gameOfLife.setLivingCell(0, 2);
            gameOfLife.setLivingCell(1, 0);
            gameOfLife.setLivingCell(1, 1);
    
            assertTrue(gameOfLife.isAlive(0, 1));
            assertTrue(gameOfLife.isAlive(1, 1));
            gameOfLife.nextGeneration();
            assertFalse(gameOfLife.isAlive(0, 1));
            assertFalse(gameOfLife.isAlive(1, 1));
        }
    
        /**
         * Nouvelle Génération - Staying Alive
         * @throws OutOfRangeException 
         */
        @Test void aliveAndTwoOrThreeNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
            gameOfLife.setLivingCell(0, 1);
            gameOfLife.setLivingCell(0, 2);
            gameOfLife.setLivingCell(1, 0);
            gameOfLife.setLivingCell(1, 1);
    
            assertTrue(gameOfLife.isAlive(0, 0));
            assertTrue(gameOfLife.isAlive(1, 0));
            gameOfLife.nextGeneration();
            assertTrue(gameOfLife.isAlive(0, 0));
            assertTrue(gameOfLife.isAlive(1, 0));
        }
    
        /**
         * Nouvelle Génération - Expansion
         * @throws OutOfRangeException 
         */
        @Test void deadAndThreeNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
            gameOfLife.setLivingCell(0, 1);
            gameOfLife.setLivingCell(0, 2);
            gameOfLife.setLivingCell(1, 0);
            gameOfLife.setLivingCell(1, 1);
    
            assertFalse(gameOfLife.isAlive(1, 2));
            gameOfLife.nextGeneration();
            assertTrue(gameOfLife.isAlive(1, 2));
        }
    
        /**
         * Nouvelle Génération - Non Expansion
         * @throws OutOfRangeException 
         */
        @Test void deadAndMoreThanThreeNeighbors() throws OutOfRangeException {
            gameOfLife.setLivingCell(0, 0);
            gameOfLife.setLivingCell(0, 1);
            gameOfLife.setLivingCell(0, 2);
            gameOfLife.setLivingCell(1, 0);
            gameOfLife.setLivingCell(1, 1);
            gameOfLife.setLivingCell(2, 2);
    
            assertFalse(gameOfLife.isAlive(1, 2));
            gameOfLife.nextGeneration();
            assertFalse(gameOfLife.isAlive(1, 2));
        }
    }


    private GameOfLife gameOfLife;
}
